apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushowl-backend-minikube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pushowl/pushowl-backend-argocd-test
    targetRevision: main
    path: pushowl-backend
    helm:
      valueFiles:
        - values-minikube.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pushowl-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true