apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-env
  labels:
    app: {{ .Chart.Name }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
